from typing import Union, Callable, Iterable, Any, Optional


def tokenize(s: str, tokenizer: Union[None, str, Callable, Any]) -> Iterable[str]:
    """
    Tokenizes the input string `s` based on the given tokenizer.

    Args:
        s: The input string to tokenize.
        tokenizer: The tokenizer used to split `s`. Can be one of the following:
            - None: Splits `s` by whitespace characters.
            - str: Splits `s` by the given string.
            - Callable: Splits `s` by calling the provided callable object on `s`.
            - Any object with a `split` method.

    Returns: A sequence of tokens generated by the tokenizer.

    Examples:
        >>> tokenize("Hello, world!", None)
        ['Hello,', 'world!']

        >>> tokenize("This is a test string.", " ")
        ['This', 'is', 'a', 'test', 'string.']

        >>> tokenize("This is a test string.", lambda x: x.split())
        ['This', 'is', 'a', 'test', 'string.']

        >>> class CustomTokenizer:
        ...     def split(self, s):
        ...         return s.split(".")
        ...
        >>> tokenize("This is a test. Another sentence.", CustomTokenizer())
        ['This is a test', ' Another sentence', '']
    """
    if not tokenizer:
        return s.split()
    elif isinstance(tokenizer, str):
        return s.split(tokenizer)
    elif hasattr(tokenizer, 'split') and callable(tokenizer.split):
        return tokenizer.split(s)
    elif callable(tokenizer):
        return tokenizer(s)
    else:
        raise ValueError(f"tokenizer '{tokenizer}' is not supported")


def num_overlap_tokens(
        str1: str,
        str2: str,
        tokenizer: Optional[Union[str, Callable]] = None
) -> int:
    """
    Returns the number of overlapping tokens between two strings.

    Args:
        str1: The first string.
        str2: The second string.
        tokenizer: The tokenizer used to split the strings into tokens.
            - None: Splits by whitespace.
            - str: Splits by the given string separator.
            - Callable: A function that takes a string and returns a list of tokens.

    Returns:
        int: The number of tokens that appear in both strings.

    Examples:
        >>> num_overlap_tokens("hello world", "world hello")
        2
        >>> num_overlap_tokens("a,b,c", "b,c,d", tokenizer=",")
        2
        >>> num_overlap_tokens("foo bar", "baz qux")
        0
    """
    if not tokenizer:
        str1 = set(str1.split())
        str2 = set(str2.split())
    elif isinstance(tokenizer, str):
        str1 = set(str1.split(tokenizer))
        str2 = set(str2.split(tokenizer))
    elif callable(tokenizer):
        str1 = set(tokenizer(str1))
        str2 = set(tokenizer(str2))
    return len(str1.intersection(str2))
