from rich_python_utils.production_utils.common._constants.path import SupportedLocales

RISK_SINGLE_TOKEN_NLU_HYPOTHESIS_SUBSTRINGS = (
    'QAIntent',
)

UTTERANCE_REPLACE = [
    ('x. box', 'xbox'),
    ('iheart radio', 'iheartradio'),
    ('no alexa', 'alexa'),
    ('coco melon', 'cocomelon'),
    ('playlist playlist', 'playlist'),
    ('my my playlist', 'my playlist')
]

PRE_DEFINED_REWRITES = [
    (
        'play then again',
        'play that again',
        'Music|MusicControlIntent|Anaphor:that|ControlAction:again'
    ),
    (
        'play music by l. o. f. i. z. e.',
        'play music by lofive',
        'Music|MusicControlIntent|ArtistName:lofive'
    )
]

HIGH_RISK_UTTERANCE_PREFIX_INCOMPLETE = [
    'turn on',
    'turn on the',
    'turn off the',
    'turn',
    'turn the',
    'power',
    'power on the',
    'power off the',
    'power the',
    'make',
    'make the',
    'shop for',
    'alarm at',
    'an alarm at',
    'timer at',
    'a timer at',
    'an timer at',
    'a alarm',
    'an alarm',
    'a timer',
    'an timer',
    'alarm for',
    'timer for',
    'a alarm for',
    'an alarm for',
    'a timer for',
    'an timer for',
    'set alarm for',
    'set timer for',
    'set a alarm for',
    'set an alarm for',
    'set a timer for',
    'set an timer for',
    "wake up at",
    "set a",
    "set me a",
    'switch',
    'switch on the',
    'switch off the',
    'shut',
    'shut off the',
    'shut down the',
    'shut the',
    'delete',
    'remove',
    'read me',
    'call',
    'how far is'
]

HIGH_RISK_UTTERANCE_PREFIX = [
    'turn off',
    'turn off all',
    'power on',
    'power off',
    'alarm',
    'timer',
    'set alarm',
    'set timer',
    'switch on',
    'switch off',
    'shut off',
    'shut down',
    'shut up',
    'schedule',
    'end call',
    'cancel',
    *HIGH_RISK_UTTERANCE_PREFIX_INCOMPLETE
]

MORE_UTTERANCE_PREFIX_INCOMPLETE = [
    'go to',
    'go to the',
    'take me to',
    'take me to the',
    'go back to',
    'go back to the',
    'play',
    'play the',
    'play chapter',
    'play episode',
    'read',
    'read chapter',
    'open',
    'put',
    'show',
    'set',
    'choose',
    'find',
    'disable',
    'connect',
    'disconnect',
    'disconnect the',
    'pair',
    'search',
    'master',
    'can you',
    'how do you',
    'what does',
    'is it',
    'are you',
    'do you',
    'show me',
    'where is',
    'where are',
    'where',
    'why',
    'why is',
    'why is the',
    'what is',
    'what is the',
    "what's the",
    'what is my',
    'what are my',
    "what's",
    "what's my",
    "what my",
    'what are',
    'what are the',
    'what',
    'who',
    'who is',
    'who is the',
    'who is this',
    'who is that',
    'how are',
    'how',
    'how is',
    'how is the',
    'how long',
    'how long is',
    'how much',
    'how many',
    'when is',
    'when is the',
    'when',
    'what do i',
    'does',
    'get',
    'let me have a',
    'the truth is',
    "what do you do when i'm"
]

COMMON_UTTERANCE_PREFIX = [
    *HIGH_RISK_UTTERANCE_PREFIX,
    *MORE_UTTERANCE_PREFIX_INCOMPLETE,
    'go back'
    'replay',
    'start',
    'restart',
    'shuffle',
    'repeat',
    'resume',
    'continue',
    'close',
    'quit',
    'exit',
    'stop',
    'pause',
    'skip',
    'next',
    'how many days',
    'how many more days'
]
IGNORED_UTTERANCES_FOR_QUERIES_AND_REWRITES = {
    *COMMON_UTTERANCE_PREFIX,
    'hi',
    'hello',
    'hey',
    'meow',
    'hang up',
    'good night',
    'cancel timer',
    'cancel alarm',
    'notification',
    'announcement',
    'never mind',
    'select',
    'sure',
    'sing',
    'try it',
    'start over',
    'ok',
    'okay',
    'go',
    'please',
    'please play',
    'light on',
    'play again',
    'yes',
    'yes please',
    "what's today",
    "play the song",
    'yes yes',
    'yeah',
    'thank you',
    'thank you yeah',
    'go home',
    'home',
    'rewind',
    'dismiss',
    'back',
    'next song',
    'next step',
    'stop stop',
    'stop it',
    'stop no',
    'is this',
    "what's this",
    "what is this",
    "what song is this",
    'stop please',
    'stop playing',
    'stop alexa',
    'please stop',
    'no',
    'oh',
    'oh no',
    'no no',
    'no thank you',
    'no stop',
    'no alexa',
    'no never',
    'no please',
    'off',
    'add',
    'end',
    'quiet',
    'be quiet',
    'shush',
    'play music',
    'sorry',
    'fuck you',
    'sleep timer',
    "i'm sorry",
    "play msnbc",
    'what did you hear',
    'what did i say',
    'show me things',
    'show me things to do nearby',
    'name of song',
    'name of this song',
    'who made this song',
    'how long is this',
    'how long is this song',
    'what do we what',
    'what do i wear',
    'play my liked songs',
    'play my likes',
    'i have a question'
}
IGNORED_UTTERANCES_FOR_QUERIES = {
    'play spotify',
    'come on',
    'disgusting'
}
IGNORED_UTTERANCES_FOR_QUERIES_BY_LOCALE = {
    SupportedLocales.EN_GB: {
        'read me a bedtime story',
        'tell me a bedtime story',
        'read a bedtime story',
        'tell a bedtime story',
        'play bedtime story'
    }
}
IGNORED_UTTERANCES_FOR_REWRITES = {
    'can you play'
}
IGNORED_UTTERANCES_FOR_REWRITES_BY_LOCALE = {}
IGNORED_UTTERANCE_PATTERNS_FOR_QUERIES = []
IGNORED_UTTERANCE_PATTERNS_FOR_REWRITES = [
    '*fuck',
    '*asshole'
]
IGNORED_UTTERANCE_PATTERNS_FOR_QUERIES_AND_REWRITES = []
