NAME_SUFFIX_FIRST = '_first'
NAME_SUFFIX_SECOND = '_second'
NAME_PREFIX_AVG = 'avg_'
NAME_PREFIX_MAX = 'max_'
NAME_PREFIX_SUM = 'sum_'

KEY_COUNT = 'count'
KEY_OCCURRENCES = 'occurrences'
KEY_TIMESTAMP = 'timestamp'
KEY_LOCAL_TIMESTAMP = 'local_timestamp'
KEY_UUID = 'uuid'
KEY_CUSTOMER_ID = 'customer_id'
KEY_PERSON_ID = 'person_id'
KEY_TOP1_CHOICE = 'is_top1'
