from rich_python_utils.production_utils.greenwich_data.constants import (
    NAME_PREFIX_SUM,
    NAME_PREFIX_CUSTOMER,
    NAME_PREFIX_CUSTOMER_AVG,
    NAME_PREFIX_GLOBAL_AVG,
    KEYS_DEFECTIVE_SIGNALS,
    KEY_DEFECT
)

KEY_HISTORY_LIST_PROD = 'history_requests'
KEY_HISTORY_LIST = 'hist_requests'
KEY_HISTORY_ITEM_ID = 'hist_id'

(
    GLOBAL_AVG_DEFECT_BARGEIN,
    GLOBAL_AVG_DEFECT_REPHRASE,
    GLOBAL_AVG_DEFECT_TERMINATION,
    GLOBAL_AVG_DEFECT_UNHANDLED,
    GLOBAL_AVG_DEFECT_SANDPAPER,
) = KEYS_GLOBAL_AVG_DEFECTIVE_SIGNALS = tuple(
    (NAME_PREFIX_GLOBAL_AVG + signal_name) for signal_name in KEYS_DEFECTIVE_SIGNALS
)

(
    CUSTOMER_AVG_DEFECT_BARGEIN,
    CUSTOMER_AVG_DEFECT_REPHRASE,
    CUSTOMER_AVG_DEFECT_TERMINATION,
    CUSTOMER_AVG_DEFECT_UNHANDLED,
    CUSTOMER_AVG_DEFECT_SANDPAPER,
) = KEYS_CUSTOMER_AVG_DEFECTIVE_SIGNALS = tuple(
    (NAME_PREFIX_CUSTOMER_AVG + signal_name) for signal_name in KEYS_DEFECTIVE_SIGNALS
)

# region prod internal keys
KEY_SUM_DEFECT = NAME_PREFIX_SUM + KEY_DEFECT
(
    KEY_SUM_DEFECT_BARGEIN,
    KEY_SUM_DEFECT_REPHRASE,
    KEY_SUM_DEFECT_TERMINATION,
    KEY_SUM_DEFECT_UNHANDLED,
    KEY_SUM_DEFECT_SANDPAPER,
) = KEYS_SUM_DEFECTIVE_SIGNALS = tuple(
    (NAME_PREFIX_SUM + signal_name) for signal_name in KEYS_DEFECTIVE_SIGNALS
)
(
    KEY_PROD_CUSTOMER_SUM_DEFECT_BARGEIN,
    KEY_PROD_CUSTOMER_SUM_DEFECT_REPHRASE,
    KEY_PROD_CUSTOMER_SUM_DEFECT_TERMINATION,
    KEY_PROD_CUSTOMER_SUM_DEFECT_UNHANDLED,
    KEY_PROD_CUSTOMER_SUM_DEFECT_SANDPAPER,
) = KEYS_PROD_CUSTOMER_SUM_DEFECTIVE_SIGNALS = tuple(
    (NAME_PREFIX_CUSTOMER + NAME_PREFIX_SUM + signal_name) for signal_name in KEYS_DEFECTIVE_SIGNALS
)
# endregion

# region filtering

DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_SIZE = 105
DEFAULT_CUSTOMER_HISTORY_FILTER_MIN_GLOBAL_COUNT = 2
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_GLOBAL_AVG_DEFECT = 0.2
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_CUSTOMER_AVG_DEFECT_FOR_GLOBAL_SELECTION = 1.0
DEFAULT_CUSTOMER_HISTORY_FILTER_MIN_CUSTOMER_COUNT_FOR_PERSONALIZED_SELECTION_LEVEL1 = 2
DEFAULT_CUSTOMER_HISTORY_FILTER_MIN_CUSTOMER_COUNT_FOR_PERSONALIZED_SELECTION_LEVEL2 = 3
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_CUSTOMER_AVG_DEFECT = 0.2
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_GLOBAL_AVG_DEFECT_FOR_PERSONALIZED_SELECTION = 0.5
DEFAULT_CUSTOMER_HISTORY_FILTER_MIN_CUSTOMER_COUNT_EXT_PERSONALIZED_SELECTION = 2
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_CUSTOMER_AVG_DEFECT_EXT_PERSONALIZED_SELECTION = 0.15
DEFAULT_CUSTOMER_HISTORY_FILTER_MIN_GLOBAL_COUNT_EXT_PERSONALIZED_SELECTION = 30
DEFAULT_CUSTOMER_HISTORY_FILTER_MAX_GLOBAL_AVG_DEFECT_EXT_PERSONALIZED_SELECTION = 0.3
DEFAULT_CUSTOMER_HISTORY_BLOCKED_DOMAINS = {'Knowledge'}

DEFAULT_CUSTOMER_HISTORY_BLOCKED_PROVIDERS = {
    'AsrDisambiguation',
    'AsrDisambiguationMacawRules',
    'ContextualQr',
    'Blueprints',
    'MultiTurnBasedRewrite',
}
# endregion
