KEY_MERGED_FEATURES = 'merged_features'
KEY_FEATURE_GROUP = 'feature_group'
KEY_LABEL = 'label'
KEY_SCORE = 'score'
KEY_RESULT = 'result'
FILENAME_FEATURE_LIST = 'feature_list.txt'
DIRNAME_FEATURE_DATA = 'feature_data'
